name: Sonar
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner
        
      - name: Begin sonarscanner
        run: dotnet sonarscanner begin /k:"PhilBroderickFS_Sonar-Test" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /o:"philbroderickfs" /d:sonar.cs.opencover.reportsPath="**/coverage.opencover.xml" /d:sonar.cs.vstest.reportsPath="**/*.trx"
        
      - name: dotnet build
        run: dotnet build
        
      - name: dotnet test
        run: dotnet test --settings coverlet.runsettings --logger:trx
        
      - name: end sonarscanner
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}